In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])

In [4]:
b = np.array([[1,2,3,4]])


In [12]:
c = np.array([[1,2,3,4],[4,3,2,1]])

In [14]:
d = np.array([[1],[2],[3],[4]])


In [15]:
m = np.random.rand(5,5)


In [18]:
n = np.random.randn(4,4)
n

array([[ 0.39939984,  0.52199412,  0.7504093 , -1.4301611 ],
       [ 0.84821967, -0.4030927 , -0.53697969,  0.05627637],
       [ 1.13159122, -0.42373961, -0.50508654, -1.66508176],
       [ 1.90402664, -0.12899463, -0.6009087 , -1.07047267]])

In [17]:
n+1

array([[0.47366442, 0.90653825, 2.12803014, 1.36762713],
       [0.87671605, 1.72005284, 0.60702308, 0.10042322],
       [0.70860042, 0.89037532, 1.63004339, 1.70759362],
       [2.74633613, 2.51154573, 0.74422571, 2.2685624 ]])

In [21]:
x = np.zeros((3,3))
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
x+3

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [24]:
(x+2)*5

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

矩阵的运算




In [29]:
a = np.array([[1,2],[1,2]])

a

array([[1, 2],
       [1, 2]])

In [31]:
print(a+1)

[[2 3]
 [2 3]]


In [32]:
b = np.array([[1,2],[1,2]])
print(a*b)

[[1 4]
 [1 4]]


In [33]:
print(np.dot(a,b))

[[3 6]
 [3 6]]


In [34]:
b.T

array([[1, 1],
       [2, 2]])

矩阵的拼接


In [35]:
np.hstack((a,b))


array([[1, 2, 1, 2],
       [1, 2, 1, 2]])

In [36]:
np.vstack((a,b))

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])